### ISSUE TITLE
Update `utrecht-accordion-section` door de margin CSS-property te vervangen door de row-gap-property.

### ISSUE THREAD

**Issue by AliKdhim87** [frameless/strapi#794]
**Beschrijving:**

Het probleem is dat de accordion-component altijd extra marge krijgt, ook als hij is ingeklapt.

Mogelijke oplossing:

```scss
@mixin utrecht-accordion {
  display: grid;
  row-gap: var(--utrecht-accordion-row-gap);
}

```

Zie ook bijvoorbeeld https://www.nldesignsystem.nl/button/ als gebruiker van de versie met dit probleem
